name: Approve PR on Comment
on:
  issue_comment:
    types: [created]

jobs:
  approve:
    runs-on: ubuntu-latest

    steps:
    - name: Get current branch name
      run: | 
        echo "Current branch: $GITHUB_HEAD_REF"
