name: Approve PR on Comment
on:
  issue_comment:
    types: [created]

jobs:
  approve:
    runs-on: ubuntu-latest

    steps:
      - name: Get current branch name
        run: |
          pull_request=$(curl -s -H "Authorization: Bearer $TOKEN" https://api.github.com/repos/$GITHUB_REPOSITORY/pulls/$GITHUB_EVENT_NUMBER)
          current_branch=$(echo $pull_request | jq -r '.head.ref')
          echo "Current branch: $current_branch"
