name: Comment Jira Number
on:
  pull_request_review:
    types: [submitted]

jobs:
  extract-jira-number:
    runs-on: ubuntu-latest
    steps:
    - name: Check if review is approved
      if: ${{ github.event.review.state == 'approved' }}
      run: |
        pr_number=${{ github.event.pull_request.number }}
        repo_name=${{ github.event.repository.name }}
        repo_owner=${{ github.event.repository.owner.login }}
        commit_message=$(
          curl \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"\
            https://api.github.com/repos/$repo_owner/$repo_name/pulls/$pr_number/commits | jq -r .[0].commit.message
        )
        
        jira_number=$(echo $commit_message | grep -oP 'off-[0-9]+')
        echo "Posting comment with Jira ticket number $jira_number on PR #$pr_number in $repo_owner/$repo_name."

        curl \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"\
          https://api.github.com/repos/$repo_owner/$repo_name/issues/$pr_number/comments\
          -d "{\"body\":\"$jira_number\"}"
