name: Comment Jira Number
on:
  pull_request_review:
    types: [submitted]

jobs:
  extract-jira-number:
    runs-on: ubuntu-latest
    steps:
    - name: Check if review is approved
      id: jira-ticket-number
      if: ${{ github.event.review.state == 'approved' }}
      run: |
        pr_number=${{ github.event.pull_request.number }}
        repo_name=${{ github.event.repository.name }}
        repo_owner=${{ github.event.repository.owner.login }}
        commit_message=$(
          curl \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"\
            https://api.github.com/repos/$repo_owner/$repo_name/pulls/$pr_number/commits | jq -r .[0].commit.message
        )
        
        echo "jira_number=$(echo $commit_message | grep -oP 'off-[0-9]+')" >> $GITHUB_OUTPUT

    - name: Comment PR
      if: ${{ github.event.review.state == 'approved' }}
      uses: thollander/actions-comment-pull-request@v2
      with:
        message: |
          ${{ steps.jira-ticket-number.output.jira_number }}
